// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BusinessElectricityConsumption: typeof import('./components/corporatePortrait/businessElectricityConsumption.vue')['default']
    BusinessRankings: typeof import('./components/doubleCarbon/businessRankings.vue')['default']
    ConstructionProgress: typeof import('./components/pandect/constructionProgress.vue')['default']
    CorporateIntellectualProperty: typeof import('./components/corporatePortrait/corporateIntellectualProperty.vue')['default']
    EconomicalOperation: typeof import('./components/corporatePortrait/economicalOperation.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElectricityUsage: typeof import('./components/doubleCarbon/electricityUsage.vue')['default']
    ElectricityUsedProportion: typeof import('./components/doubleCarbon/electricityUsedProportion.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EnterpriseAssociationMap: typeof import('./components/corporatePortrait/enterpriseAssociationMap.vue')['default']
    EnterpriseMap: typeof import('./components/enterprise/enterpriseMap.vue')['default']
    EnterpriseProducts: typeof import('./components/corporatePortrait/enterpriseProducts.vue')['default']
    EnterpriseProgress: typeof import('./components/enterprise/enterpriseProgress.vue')['default']
    EnterpriseRiskCom: typeof import('./components/publicOpinionMonitoring/enterpriseRiskCom.vue')['default']
    EnterpriseSubItemization: typeof import('./components/corporatePortrait/enterpriseSubItemization.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Income: typeof import('./components/pandect/income.vue')['default']
    IncomeCopy: typeof import('./components/pandect/incomeCopy.vue')['default']
    IndustryRanking: typeof import('./components/pandect/industryRanking.vue')['default']
    LoginSuccessPop: typeof import('./components/loginSuccessPop.vue')['default']
    NewRisk: typeof import('./components/publicOpinionMonitoring/newRisk.vue')['default']
    OverviewPage: typeof import('./components/corporatePortrait/overviewPage.vue')['default']
    PandectMap: typeof import('./components/pandect/pandectMap.vue')['default']
    RiskIndex: typeof import('./components/corporatePortrait/riskIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubItemization: typeof import('./components/enterprise/subItemization.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
